# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 The Phantex Authors

"""
Phantex — Q1: Global Model Trainer.

Trains the 3-stage ensemble (IF + XGBoost + AE) on synthetic attack data
to produce a universal starter model. This model ships with Phantex and
provides immediate ML protection before any tenant data is available.

Security:
  - Trained model is signed with HMAC-SHA256 manifest (J5e)
  - Training is fully reproducible (seeded RNG)
  - No external data dependency
  - All model artifacts are validated before registration
"""

from __future__ import annotations

import time
from typing import Any

import numpy as np
import structlog

from ml.config import get_ml_config
from ml.global_model.synthetic_generator import GlobalSyntheticGenerator
from ml.integrity.audit import AuditAction, TrainingAuditLog
from ml.models.autoencoder import AutoencoderModel
from ml.models.isolation_forest import IsolationForestModel
from ml.models.xgboost_model import XGBoostModel
from ml.provenance.manifest import DataProvenance, ManifestBuilder, ValidationMetrics
from ml.training.validator import ModelValidator

logger = structlog.get_logger("phantex.ml.global_model.trainer")

class GlobalModelTrainer:
    """Train the global starter model on synthetic attack data.

    The global model is a full 3-stage ensemble trained on high-fidelity
    synthetic data across all 8 attack classes. It provides baseline
    detection capability from the first event.

    Training pipeline:
      1. Generate synthetic data (50K samples, 62 features, 8 classes)
      2. Sanitize data (J5b)
      3. Split train/validation
      4. Train IF (unsupervised on all data)
      5. Train XGBoost (supervised on all labeled data)
      6. Train AE (on benign subset)
      7. Adversarial augment + retrain AE (J5a)
      8. Validate all stages
      9. Generate signed manifest (J5e)
      10. Return trained models + metadata
    """

    def __init__(self) -> None:
        self._validator = ModelValidator()
        self._manifest_builder = ManifestBuilder(pipeline_version="q1-global")

    def train(
        self,
        n_samples: int | None = None,
        random_state: int = 42,
        operator_id: str = "system",
    ) -> dict[str, Any]:
        """Train the global starter model.

        Args:
            n_samples: Override sample count (default from config).
            random_state: RNG seed for reproducibility.
            operator_id: Operator/system identifier for audit trail.

        Returns:
            Dict with:
              - stage1: IsolationForestModel (trained)
              - stage2: XGBoostModel (trained)
              - stage3: AutoencoderModel (trained)
              - feature_names: list of 62 feature names
              - metrics: validation results
              - manifest: signed training manifest
              - data_fingerprint: SHA-256 of training data
              - audit_chain_valid: bool
        """
        cfg = get_ml_config().global_model
        start = time.time()
        audit = TrainingAuditLog()

        audit.append(
            AuditAction.TRAINING_STARTED,
            actor=operator_id,
            tenant_id=cfg.global_tenant_id,
            details={"model_type": "global_starter", "random_state": random_state},
        )

        # ── Step 1: Generate synthetic data ──────────────────────────
        sample_count = n_samples or cfg.synthetic_samples
        generator = GlobalSyntheticGenerator(random_state=random_state)
        X, y, feature_names = generator.generate(
            n_samples=sample_count,
            anomaly_fraction=cfg.anomaly_fraction,
            n_features=cfg.n_features,
        )
        data_fingerprint = generator.data_fingerprint(X, y)

        audit.append(
            AuditAction.DATA_LOADED,
            actor=operator_id,
            tenant_id=cfg.global_tenant_id,
            details={
                "samples": len(X),
                "features": len(feature_names),
                "anomaly_fraction": cfg.anomaly_fraction,
                "data_fingerprint": data_fingerprint[:16],
            },
        )

        # ── Step 2: Validate data (skip sanitization for synthetic data) ─
        # Synthetic data is generated by us with known-good distributions,
        # so we skip the outlier sanitizer to avoid removing extreme-but-valid
        # attack profiles (e.g., DoS has deliberately extreme values).
        # We still validate basic data integrity.
        X_clean = X.copy()
        y_clean = y.copy()
        # Replace any NaN/Inf that might sneak in (defensive)
        X_clean = np.nan_to_num(X_clean, nan=0.0, posinf=0.0, neginf=0.0)
        n_invalid = int(np.isnan(X).any(axis=1).sum() + np.isinf(X).any(axis=1).sum())

        audit.append(
            AuditAction.SANITIZATION_COMPLETE,
            actor="system",
            tenant_id=cfg.global_tenant_id,
            details={
                "skipped_reason": "synthetic_data_known_good",
                "invalid_rows_cleaned": n_invalid,
                "retained_samples": len(X_clean),
            },
        )

        # ── Step 3: Train/Validation split ───────────────────────────
        n = X_clean.shape[0]
        split = int(n * 0.8)  # 80/20 split
        X_train, X_val = X_clean[:split], X_clean[split:]
        y_train, y_val = y_clean[:split], y_clean[split:]

        results: dict[str, Any] = {
            "n_samples": n,
            "n_features": len(feature_names),
            "feature_names": feature_names,
            "data_fingerprint": data_fingerprint,
            "sanitization": {"skipped": True, "reason": "synthetic_data"},
        }

        # ── Step 4: Stage 1 — Isolation Forest ──────────────────────
        logger.info("training_global_stage1_isolation_forest")
        stage1 = IsolationForestModel()
        s1_meta = stage1.fit(X_train, feature_names=feature_names)
        s1_scores = stage1.predict_score(X_val)
        s1_preds = (s1_scores > 0.5).astype(int)
        s1_val = self._validator.validate(y_val, s1_preds)
        results["stage1"] = {
            "model": stage1,
            "training_meta": s1_meta,
            "validation": s1_val,
        }
        logger.info(
            "global_stage1_trained",
            precision=round(s1_val.precision, 3),
            recall=round(s1_val.recall, 3),
        )

        # ── Step 5: Stage 2 — XGBoost ───────────────────────────────
        logger.info("training_global_stage2_xgboost")
        stage2 = XGBoostModel()
        s2_meta = stage2.fit(X_train, y_train, feature_names=feature_names)
        s2_probs = stage2.predict_proba(X_val)
        s2_preds = (s2_probs[:, 0] < 0.5).astype(int)  # Non-benign
        s2_val = self._validator.validate(y_val, s2_preds)
        results["stage2"] = {
            "model": stage2,
            "training_meta": s2_meta,
            "validation": s2_val,
        }
        logger.info(
            "global_stage2_trained",
            precision=round(s2_val.precision, 3),
            recall=round(s2_val.recall, 3),
        )

        # ── Step 6: Stage 3 — Autoencoder (benign data only) ────────
        benign_mask = y_train == 0
        X_benign = X_train[benign_mask]
        n_benign = len(X_benign)

        logger.info("training_global_stage3_autoencoder", benign_samples=n_benign)
        stage3 = AutoencoderModel(input_dim=len(feature_names))
        s3_meta = stage3.fit(X_benign, feature_names=feature_names)
        s3_scores = stage3.predict_score(X_val)
        s3_preds = (s3_scores > 0.5).astype(int)
        s3_val = self._validator.validate(y_val, s3_preds)
        results["stage3"] = {
            "model": stage3,
            "training_meta": s3_meta,
            "validation": s3_val,
        }
        logger.info(
            "global_stage3_trained",
            precision=round(s3_val.precision, 3),
            recall=round(s3_val.recall, 3),
        )

        # ── Step 7: Adversarial augmentation (J5a) ──────────────────
        if stage3.is_fitted:
            try:
                from ml.adversarial.adversarial_trainer import augment_training_data

                X_aug, _ = augment_training_data(
                    model=stage3._model,
                    X_train=X_benign.astype(np.float32),
                    epsilon=0.1,
                    adversarial_ratio=0.3,
                )
                stage3_hardened = AutoencoderModel(input_dim=len(feature_names))
                stage3_hardened.fit(X_aug, feature_names=feature_names)
                results["stage3"]["model"] = stage3_hardened
                results["stage3"]["adversarial_augmented"] = True
                results["stage3"]["augmented_samples"] = len(X_aug)
                logger.info(
                    "global_stage3_adversarial_augmented",
                    original=n_benign,
                    augmented=len(X_aug),
                )
            except Exception as exc:
                logger.warning("global_adversarial_augmentation_failed", error=str(exc))
                results["stage3"]["adversarial_augmented"] = False

        # ── Step 8: Generate signed manifest (J5e) ──────────────────
        manifest = self._manifest_builder.build(
            model_id=f"{cfg.global_tenant_id}:{int(start)}",
            data=DataProvenance(
                total_samples=n,
                positive_labels=int((y_clean > 0).sum()),
                negative_labels=int((y_clean == 0).sum()),
                sanitization_report={"skipped": True, "reason": "synthetic_data"},
            ),
            validation=ValidationMetrics(
                clean_precision=s1_val.precision,
                clean_recall=s1_val.recall,
                clean_fpr=s1_val.fpr,
            ),
        )
        manifest = self._manifest_builder.sign(manifest)
        results["manifest"] = manifest.to_dict()

        audit.append(
            AuditAction.TRAINING_COMPLETED,
            actor=operator_id,
            tenant_id=cfg.global_tenant_id,
            details={
                "training_time_seconds": round(time.time() - start, 1),
                "manifest_hash": manifest.content_hash()[:16],
                "data_fingerprint": data_fingerprint[:16],
            },
        )
        results["audit_chain_valid"] = audit.verify_chain()

        elapsed = time.time() - start
        results["training_time_seconds"] = elapsed
        logger.info(
            "global_model_training_complete",
            elapsed_seconds=f"{elapsed:.1f}",
            data_fingerprint=data_fingerprint[:16],
        )

        return results
