# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 The Phantex Authors

"""
Phantex — Local IoC Engine.

SHA-256 hashed Indicators of Compromise generated by ML meta-detection
modules.  Stores locally with dedup + TTL-based expiry; designed for
air-gapped deployments where no data leaves the network by default.

Indicator types:
  - IPv4/IPv6 addresses
  - Domain names
  - Payload hashes (file SHA-256)
  - Attack signatures (PRL rule match fingerprints)
  - URLs
  - Email addresses
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

class IoCType(StrEnum):
    """Indicator of Compromise type."""

    IPV4 = "ipv4"
    IPV6 = "ipv6"
    DOMAIN = "domain"
    URL = "url"
    EMAIL = "email"
    FILE_HASH = "file_hash"
    ATTACK_SIGNATURE = "attack_signature"

class IoCSeverity(StrEnum):
    """Severity level for an IoC."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

_SEVERITY_ORDER: dict[str, int] = {"low": 0, "medium": 1, "high": 2, "critical": 3}

class IoCSource(StrEnum):
    """Where the IoC originated."""

    LOCAL_DETECTION = "local_detection"  # ML meta-detection module
    FEED_IMPORT = "feed_import"  # External STIX/TAXII/CSV import
    MANUAL = "manual"  # Analyst-submitted
    RULE_MATCH = "rule_match"  # PRL rule trigger

@dataclass
class Indicator:
    """A single Indicator of Compromise."""

    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    tenant_id: str = ""
    ioc_type: IoCType = IoCType.IPV4
    raw_value: str = ""  # Only stored if not hashed-only mode
    hashed_value: str = ""  # SHA-256 of raw value — always stored
    severity: IoCSeverity = IoCSeverity.MEDIUM
    source: IoCSource = IoCSource.LOCAL_DETECTION
    confidence: float = 0.0  # 0.0–1.0
    first_seen: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    last_seen: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    ttl_seconds: int = 86400 * 30  # Default: 30 days
    tags: list[str] = field(default_factory=list)
    context: dict[str, Any] = field(default_factory=dict)
    sighting_count: int = 1
    active: bool = True

    @property
    def expired(self) -> bool:
        """Check if this IoC has exceeded its TTL."""
        try:
            first = datetime.fromisoformat(self.first_seen)
            age = (datetime.now(UTC) - first).total_seconds()
            return age > self.ttl_seconds
        except (ValueError, TypeError):
            return False

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["ioc_type"] = self.ioc_type.value
        d["severity"] = self.severity.value
        d["source"] = self.source.value
        d["expired"] = self.expired
        return d

@dataclass
class CorrelationMatch:
    """A match between an incoming event and a stored IoC."""

    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    indicator_id: str = ""
    tenant_id: str = ""
    matched_value: str = ""  # The value that matched (hashed)
    matched_ioc_type: IoCType = IoCType.IPV4
    event_context: dict[str, Any] = field(default_factory=dict)
    matched_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    severity: IoCSeverity = IoCSeverity.MEDIUM

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["matched_ioc_type"] = self.matched_ioc_type.value
        d["severity"] = self.severity.value
        return d

def _sha256(value: str) -> str:
    """Compute SHA-256 hex digest of a normalized value."""
    return hashlib.sha256(value.strip().lower().encode("utf-8")).hexdigest()

class IoCEngine:
    """Local Indicator of Compromise engine.

    Stores IoCs per-tenant with dedup, TTL expiry, and live event
    correlation.  All indicators are SHA-256 hashed for privacy;
    raw values are stored only when explicitly requested.
    """

    _MAX_INDICATORS_PER_TENANT = 100_000  # Memory guard
    _MAX_MATCHES_PER_TENANT = 50_000  # Memory guard

    def __init__(self, *, store_raw: bool = False) -> None:
        self._store_raw = store_raw
        # tenant_id → {hashed_value → Indicator}
        self._indicators: dict[str, dict[str, Indicator]] = {}
        # tenant_id → [CorrelationMatch]
        self._matches: dict[str, list[CorrelationMatch]] = {}
        # tenant_id → set of hashed values for fast lookup
        self._lookup: dict[str, set[str]] = {}

    # ── Ingest IoCs ──────────────────────────────────────────────────

    def add_indicator(
        self,
        tenant_id: str,
        ioc_type: IoCType,
        value: str,
        *,
        severity: IoCSeverity = IoCSeverity.MEDIUM,
        source: IoCSource = IoCSource.LOCAL_DETECTION,
        confidence: float = 0.5,
        ttl_seconds: int = 86400 * 30,
        tags: list[str] | None = None,
        context: dict[str, Any] | None = None,
    ) -> Indicator:
        """Add or update an IoC.  Deduplicates by hashed value."""
        hashed = _sha256(value)

        if tenant_id not in self._indicators:
            self._indicators[tenant_id] = {}
            self._lookup[tenant_id] = set()

        existing = self._indicators[tenant_id].get(hashed)
        if existing:
            # Update sighting — bump last_seen and sighting count
            existing.last_seen = datetime.now(UTC).isoformat()
            existing.sighting_count += 1
            if confidence > existing.confidence:
                existing.confidence = confidence
            if _SEVERITY_ORDER.get(severity.value, 0) > _SEVERITY_ORDER.get(existing.severity.value, 0):
                existing.severity = severity
            existing.active = True
            return existing

        indicator = Indicator(
            tenant_id=tenant_id,
            ioc_type=ioc_type,
            raw_value=value if self._store_raw else "",
            hashed_value=hashed,
            severity=severity,
            source=source,
            confidence=confidence,
            ttl_seconds=ttl_seconds,
            tags=tags or [],
            context=context or {},
        )

        self._indicators[tenant_id][hashed] = indicator
        self._lookup[tenant_id].add(hashed)

        # Memory guard — evict oldest
        if len(self._indicators[tenant_id]) > self._MAX_INDICATORS_PER_TENANT:
            self._evict_oldest(tenant_id)

        return indicator

    def add_indicators_bulk(
        self,
        tenant_id: str,
        indicators: list[dict[str, Any]],
    ) -> int:
        """Bulk-add indicators.  Returns count of new indicators added."""
        added = 0
        for item in indicators:
            ioc_type = IoCType(item.get("ioc_type", "ipv4"))
            value = item.get("value", "")
            if not value:
                continue
            ind = self.add_indicator(
                tenant_id,
                ioc_type,
                value,
                severity=IoCSeverity(item.get("severity", "medium")),
                source=IoCSource(item.get("source", "feed_import")),
                confidence=float(item.get("confidence", 0.5)),
                tags=item.get("tags", []),
                context=item.get("context", {}),
            )
            if ind.sighting_count == 1:
                added += 1
        return added

    # ── Correlation ──────────────────────────────────────────────────

    def correlate(
        self,
        tenant_id: str,
        value: str,
        *,
        ioc_type: IoCType | None = None,
        event_context: dict[str, Any] | None = None,
    ) -> CorrelationMatch | None:
        """Check a value against stored IoCs.  Returns a match or None."""
        hashed = _sha256(value)
        lookup = self._lookup.get(tenant_id, set())
        if hashed not in lookup:
            return None

        indicator = self._indicators[tenant_id].get(hashed)
        if not indicator or not indicator.active or indicator.expired:
            return None

        # Bump sighting
        indicator.last_seen = datetime.now(UTC).isoformat()
        indicator.sighting_count += 1

        match = CorrelationMatch(
            indicator_id=indicator.id,
            tenant_id=tenant_id,
            matched_value=hashed,
            matched_ioc_type=indicator.ioc_type,
            event_context=event_context or {},
            severity=indicator.severity,
        )

        if tenant_id not in self._matches:
            self._matches[tenant_id] = []
        self._matches[tenant_id].append(match)

        # Memory guard
        if len(self._matches[tenant_id]) > self._MAX_MATCHES_PER_TENANT:
            self._matches[tenant_id] = self._matches[tenant_id][-self._MAX_MATCHES_PER_TENANT :]

        return match

    def correlate_batch(
        self,
        tenant_id: str,
        values: list[dict[str, str]],
    ) -> list[CorrelationMatch]:
        """Correlate multiple values.  Each dict needs 'value' key."""
        matches = []
        for item in values:
            value = item.get("value", "")
            if not value:
                continue
            m = self.correlate(
                tenant_id,
                value,
                event_context=item.get("context", {}),
            )
            if m:
                matches.append(m)
        return matches

    # ── Query ────────────────────────────────────────────────────────

    def get_indicators(
        self,
        tenant_id: str,
        *,
        ioc_type: IoCType | None = None,
        severity: IoCSeverity | None = None,
        source: IoCSource | None = None,
        active_only: bool = True,
        limit: int = 100,
    ) -> list[Indicator]:
        """Query stored indicators with optional filters."""
        indicators = list(self._indicators.get(tenant_id, {}).values())
        if active_only:
            indicators = [i for i in indicators if i.active and not i.expired]
        if ioc_type:
            indicators = [i for i in indicators if i.ioc_type == ioc_type]
        if severity:
            indicators = [i for i in indicators if i.severity == severity]
        if source:
            indicators = [i for i in indicators if i.source == source]
        # Sort by last_seen descending
        indicators.sort(key=lambda i: i.last_seen, reverse=True)
        return indicators[:limit]

    def get_indicator_by_value(self, tenant_id: str, value: str) -> Indicator | None:
        """Look up an indicator by raw value (hashes it first)."""
        hashed = _sha256(value)
        return self._indicators.get(tenant_id, {}).get(hashed)

    def get_matches(
        self,
        tenant_id: str,
        *,
        severity: IoCSeverity | None = None,
        limit: int = 100,
    ) -> list[CorrelationMatch]:
        """Query correlation matches."""
        matches = self._matches.get(tenant_id, [])
        if severity:
            matches = [m for m in matches if m.severity == severity]
        return matches[-limit:]

    def deactivate(self, tenant_id: str, value: str) -> bool:
        """Deactivate an IoC by value."""
        hashed = _sha256(value)
        ind = self._indicators.get(tenant_id, {}).get(hashed)
        if ind:
            ind.active = False
            return True
        return False

    def expire_stale(self, tenant_id: str) -> int:
        """Remove all expired indicators for a tenant.  Returns count removed."""
        indicators = self._indicators.get(tenant_id, {})
        expired_keys = [k for k, v in indicators.items() if v.expired]
        for k in expired_keys:
            del indicators[k]
            self._lookup.get(tenant_id, set()).discard(k)
        return len(expired_keys)

    def stats(self, tenant_id: str) -> dict[str, Any]:
        """IoC statistics for a tenant."""
        indicators = list(self._indicators.get(tenant_id, {}).values())
        active = [i for i in indicators if i.active and not i.expired]
        matches = self._matches.get(tenant_id, [])
        by_type: dict[str, int] = {}
        by_severity: dict[str, int] = {}
        for i in active:
            by_type[i.ioc_type.value] = by_type.get(i.ioc_type.value, 0) + 1
            by_severity[i.severity.value] = by_severity.get(i.severity.value, 0) + 1
        return {
            "total_indicators": len(indicators),
            "active_indicators": len(active),
            "total_matches": len(matches),
            "by_type": by_type,
            "by_severity": by_severity,
        }

    # ── Internal ─────────────────────────────────────────────────────

    def _evict_oldest(self, tenant_id: str) -> None:
        """Evict oldest indicators beyond the cap."""
        indicators = self._indicators[tenant_id]
        sorted_keys = sorted(
            indicators.keys(),
            key=lambda k: indicators[k].first_seen,
        )
        to_remove = sorted_keys[: len(sorted_keys) - self._MAX_INDICATORS_PER_TENANT]
        for k in to_remove:
            del indicators[k]
            self._lookup[tenant_id].discard(k)
