#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 The Phantex Authors

# ─────────────────────────────────────────────────────────────────────────────
# Phantex Quickstart
#
# One-command setup: generates secrets, starts all services, and opens
# the dashboard. Works for both development and production-mode deployments.
#
# Usage:
#   ./quickstart.sh              # development mode (default) — all 17 services, ~8 GB
#   ./quickstart.sh --prod       # production mode (real secrets, no debug)
#   ./quickstart.sh --lite       # lite mode — 9 services, ~2 GB (no ML/CH/Neo4j)
#   ./quickstart.sh --lite-ml    # lite + ML — 13 services, ~3.5 GB (no CH/Neo4j)
#
# Requirements: Docker 24+, Docker Compose, bash, openssl
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[phantex]${NC} $*"; }
ok()    { echo -e "${GREEN}[phantex]${NC} $*"; }
warn()  { echo -e "${YELLOW}[phantex]${NC} $*"; }
err()   { echo -e "${RED}[phantex]${NC} $*" >&2; }

# ── Parse args ──────────────────────────────────────────────────────────────
MODE="dev"
for arg in "$@"; do
  case "$arg" in
    --prod|--production) MODE="prod" ;;
    --lite)    MODE="lite" ;;
    --lite-ml) MODE="lite-ml" ;;
    --help|-h)
      echo "Usage: ./quickstart.sh [--prod|--lite|--lite-ml]"
      echo ""
      echo "  (default)   Development — all 17 services (~8 GB RAM)"
      echo "  --lite      Lite — 9 services, ~2 GB (no ML, ClickHouse, Neo4j)"
      echo "  --lite-ml   Lite + ML — 13 services, ~3.5 GB (no ClickHouse, Neo4j)"
      echo "  --prod      Production — all services, real secrets, no debug"
      exit 0
      ;;
    *) err "Unknown argument: $arg"; exit 1 ;;
  esac
done

# ── Preflight checks ───────────────────────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  err "Docker not found. Install Docker 24+ first: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  err "Docker Compose not found. Install Docker Compose v2+."
  exit 1
fi

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "0")
info "Docker version: $DOCKER_VERSION"

# Check available memory (Linux only, skip on others)
if [[ -f /proc/meminfo ]]; then
  MEM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
  MEM_GB=$((MEM_KB / 1024 / 1024))
  case "$MODE" in
    lite)    MIN_RAM=3 ;;
    lite-ml) MIN_RAM=5 ;;
    *)       MIN_RAM=7 ;;
  esac
  if [[ $MEM_GB -lt $MIN_RAM ]]; then
    warn "Only ${MEM_GB}GB RAM detected. This mode recommends ${MIN_RAM}GB+."
  fi
fi

# ── Generate secrets ────────────────────────────────────────────────────────
gen_secret() { openssl rand -base64 "$1" 2>/dev/null | tr -d '/+=' | head -c "$1"; }

if [[ "$MODE" == "prod" ]]; then
  ENV_FILE=".env.production"
  info "Mode: ${GREEN}PRODUCTION${NC}"

  if [[ -f "$ENV_FILE" ]]; then
    warn ".env.production already exists — using existing file."
    warn "Delete it and re-run to regenerate secrets."
  else
    info "Generating production secrets..."
    JWT_SECRET=$(gen_secret 64)
    DB_PASSWORD=$(gen_secret 32)
    DB_APP_PASSWORD=$(gen_secret 32)
    CH_PASSWORD=$(gen_secret 32)
    NEO4J_PASSWORD=$(gen_secret 32)
    REDIS_PASSWORD=$(gen_secret 32)
    GW_TOKEN=$(gen_secret 48)
    ADMIN_PASSWORD="$(gen_secret 20)$(openssl rand -hex 2)!A1"

    cat > "$ENV_FILE" <<EOF
# Auto-generated by quickstart.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ⚠️  NEVER commit this file to version control.

PHANTEX_ENVIRONMENT=production
PHANTEX_DEBUG=false
PHANTEX_JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${DB_PASSWORD}
PHANTEX_DB_PASSWORD=${DB_APP_PASSWORD}
PHANTEX_DB_ADMIN_PASSWORD=${DB_PASSWORD}
CLICKHOUSE_PASSWORD=${CH_PASSWORD}
NEO4J_PASSWORD=${NEO4J_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
PHANTEX_INTERNAL_TOKEN=${GW_TOKEN}
PHANTEX_DB_SSL_MODE=prefer
PHANTEX_CORS_ORIGINS=["http://localhost:3000"]
PHANTEX_WS_LEGACY_TOKEN_ENABLED=false
PHANTEX_REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

# Copilot LLM (optional)
COPILOT_PROVIDER=local
COPILOT_LOCAL_URL=http://host.docker.internal:1234/v1
COPILOT_LOCAL_MODEL=mistral
EOF

    chmod 600 "$ENV_FILE"
    ok "Secrets written to .env.production (mode 600)"
  fi

  COMPOSE_CMD="docker compose -f docker-compose.dev.yml -f docker-compose.prod.yml --env-file .env.production"
elif [[ "$MODE" == "lite" ]]; then
  info "Mode: ${CYAN}LITE${NC} (9 services, ~2 GB — no ML, ClickHouse, Neo4j)"
  COMPOSE_CMD="docker compose -f docker-compose.lite.yml"
elif [[ "$MODE" == "lite-ml" ]]; then
  info "Mode: ${CYAN}LITE + ML${NC} (13 services, ~3.5 GB — no ClickHouse, Neo4j)"
  COMPOSE_CMD="docker compose -f docker-compose.lite.yml -f docker-compose.lite-ml.yml"
else
  info "Mode: ${YELLOW}DEVELOPMENT${NC}"
  COMPOSE_CMD="docker compose -f docker-compose.dev.yml"
fi

# ── Generate gateway config (gitignored — must exist before Docker mount) ──
if [[ ! -f gateway/gateway.yaml ]]; then
  if [[ "$MODE" == "prod" ]]; then
    # Production: generate a real random token
    GW_SENSOR_TOKEN=$(gen_secret 48)
    cat > gateway/gateway.yaml <<GWEOF
log_level: info
log_format: json

grpc:
  listen_addr: "0.0.0.0:50051"
  tls_enabled: false

auth:
  tokens:
    "${GW_SENSOR_TOKEN}": "a0000000-0000-0000-0000-000000000001"

kafka:
  enabled: true
  brokers:
    - "kafka:9092"
  topic_prefix: "phantex.events"
  batch_size: 100
  batch_timeout: 1s

backend:
  url: "http://phantex-backend:8000"
  internal_token: "${PHANTEX_INTERNAL_TOKEN:-phantex-dev-internal-token}"
GWEOF
    ok "Created gateway/gateway.yaml with generated sensor token"
    info "Sensor auth token: ${GW_SENSOR_TOKEN}"
    info "Save this token — sensors need it to connect."
  else
    # Dev/lite: use the well-known dev token
    cat > gateway/gateway.yaml <<GWEOF
log_level: info
log_format: console

grpc:
  listen_addr: "0.0.0.0:50051"
  tls_enabled: false

auth:
  tokens:
    "phantex-docker-compose-dev-token-2025": "a0000000-0000-0000-0000-000000000001"

kafka:
  enabled: true
  brokers:
    - "kafka:9092"
  topic_prefix: "phantex.events"
  batch_size: 100
  batch_timeout: 1s

backend:
  url: "http://phantex-backend:8000"
  internal_token: "phantex-dev-internal-token"
GWEOF
    ok "Created gateway/gateway.yaml (dev defaults)"
  fi
fi

# ── Pull / Build ────────────────────────────────────────────────────────────
info "Pulling base images..."
$COMPOSE_CMD pull --quiet 2>/dev/null || $COMPOSE_CMD pull --ignore-buildable 2>/dev/null || true
info "Building images (this may take a few minutes on first run)..."
$COMPOSE_CMD build --quiet 2>/dev/null || $COMPOSE_CMD build

# ── Start services (staged — infra first, then apps) ───────────────────────
# On low-RAM machines (<8GB), starting all 17 containers at once causes memory
# pressure → Postgres health check flaps → Docker declares it unhealthy →
# dependent containers refuse to start. Fix: start infra alone, wait, migrate,
# then start app containers.
info "Starting infrastructure..."
$COMPOSE_CMD up -d --no-deps postgres kafka redis clickhouse neo4j phantex-trust-engine 2>/dev/null || true

# ── Wait for Postgres ───────────────────────────────────────────────────────
info "Waiting for PostgreSQL..."
TRIES=0
while [[ $TRIES -lt 120 ]]; do
  if docker exec phantex-postgres pg_isready -U phantex_admin -d phantex &>/dev/null; then
    break
  fi
  TRIES=$((TRIES + 1))
  sleep 1
done
if [[ $TRIES -ge 120 ]]; then
  err "PostgreSQL not ready after 120s. Check: docker logs phantex-postgres"
  exit 1
fi
ok "PostgreSQL ready."

# ── Run database migrations ─────────────────────────────────────────────────
info "Applying database migrations..."
# Capture output AND exit code without triggering set -e on failure.
# (set -e would kill the script inside $() before MIGRATE_RC=$? ever runs)
MIGRATE_RC=0
MIGRATE_OUTPUT=$(bash "${SCRIPT_DIR}/backend/migrations/migrate.sh" up 2>&1) || MIGRATE_RC=$?
MIGRATE_APPLIED=$(echo "$MIGRATE_OUTPUT" | grep -c '✅ applied\.' || true)
MIGRATE_SKIPPED=$(echo "$MIGRATE_OUTPUT" | grep -c 'already applied' || true)
# Check for real SQL/psql errors — not column names like "error_rate"
if [[ $MIGRATE_RC -ne 0 ]] || echo "$MIGRATE_OUTPUT" | grep -qiE '(ERROR:|FATAL:|psql:.*error|migration.*fail)'; then
  err "Migration failed (exit code: ${MIGRATE_RC}):"
  echo "$MIGRATE_OUTPUT" | grep -iE '(ERROR:|FATAL:|psql:|fail)' || echo "$MIGRATE_OUTPUT" | tail -30
  err "Tip: docker exec phantex-postgres psql -U phantex_admin -d phantex -c 'SELECT * FROM schema_migrations ORDER BY version;'"
  exit 1
fi
ok "Migrations complete — ${MIGRATE_APPLIED} applied, ${MIGRATE_SKIPPED} already up to date."

# ── Start remaining services ────────────────────────────────────────────────
info "Starting application services..."
$COMPOSE_CMD up -d

# ── Wait for health ─────────────────────────────────────────────────────────
info "Waiting for backend to become healthy..."
TRIES=0
MAX_TRIES=90
while [[ $TRIES -lt $MAX_TRIES ]]; do
  if curl -sf http://localhost:8000/healthz &>/dev/null; then
    break
  fi
  TRIES=$((TRIES + 1))
  sleep 2
done

if [[ $TRIES -ge $MAX_TRIES ]]; then
  err "Backend did not become healthy within 3 minutes."
  err "Check logs: docker logs phantex-backend"
  exit 1
fi

# ── Reset admin password in production ──────────────────────────────────────
if [[ "$MODE" == "prod" && -n "${ADMIN_PASSWORD:-}" ]]; then
  info "Setting generated admin password..."
  # Login with seed password, then change it via API
  LOGIN_RESP=$(curl -sf -X POST http://localhost:8000/api/v1/auth/login \
    -H 'Content-Type: application/json' \
    -d '{"email":"admin@phantex.dev","password":"changeme"}' 2>/dev/null || true)
  TOKEN=$(echo "$LOGIN_RESP" | grep -o '"access_token":"[^"]*"' | head -1 | cut -d'"' -f4)
  if [[ -n "$TOKEN" ]]; then
    PW_RESP=$(curl -sf -o /dev/null -w '%{http_code}' -X POST http://localhost:8000/api/v1/auth/password \
      -H 'Content-Type: application/json' \
      -H "Authorization: Bearer $TOKEN" \
      -d "{\"current_password\":\"changeme\",\"new_password\":\"$ADMIN_PASSWORD\"}" 2>/dev/null || true)
    if [[ "$PW_RESP" == "200" ]]; then
      ok "Admin password reset to generated value."
    else
      warn "Could not reset admin password (HTTP $PW_RESP). Change it manually after login."
    fi
  else
    warn "Could not authenticate as admin to reset password. Change it manually after login."
  fi
fi

# ── Print summary ───────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  PhanTeX is running!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Dashboard    → ${CYAN}http://localhost:3000${NC}"
echo -e "  Backend API  → ${CYAN}http://localhost:8000${NC}"
echo -e "  Gateway gRPC → ${CYAN}localhost:50051${NC}"
echo ""

if [[ "$MODE" == "dev" ]]; then
  echo -e "  Login:  ${YELLOW}admin@phantex.dev${NC} / ${YELLOW}changeme${NC}"
  echo -e "         (you will be prompted to change this on first login)"
  echo ""
  echo -e "  Kafka UI     → ${CYAN}http://localhost:8080${NC}"
fi

if [[ "$MODE" == "lite" || "$MODE" == "lite-ml" ]]; then
  echo -e "  Login:  ${YELLOW}admin@phantex.dev${NC} / ${YELLOW}changeme${NC}"
  echo -e "         (you will be prompted to change this on first login)"
  echo ""
  echo -e "  ${CYAN}Lite mode${NC} — rule-based detection active."
  if [[ "$MODE" == "lite" ]]; then
    echo -e "  ML detection disabled. Upgrade: ${YELLOW}./quickstart.sh --lite-ml${NC}"
  else
    echo -e "  ML detection active. ClickHouse/Neo4j disabled."
  fi
  echo -e "  Full mode: ${YELLOW}./quickstart.sh${NC}"
fi

if [[ "$MODE" == "prod" ]]; then
  echo -e "  Mode: ${GREEN}PRODUCTION${NC} — startup validators enforced"
  echo -e "  Secrets in:  ${YELLOW}.env.production${NC} (do not commit)"
  if [[ -n "${ADMIN_PASSWORD:-}" ]]; then
    echo ""
    echo -e "  ${RED}┌─────────────────────────────────────────────────┐${NC}"
    echo -e "  ${RED}│${NC}  Admin login:                                   ${RED}│${NC}"
    echo -e "  ${RED}│${NC}    Email:    ${YELLOW}admin@phantex.dev${NC}                  ${RED}│${NC}"
    echo -e "  ${RED}│${NC}    Password: ${YELLOW}${ADMIN_PASSWORD}${NC}  ${RED}│${NC}"
    echo -e "  ${RED}│${NC}                                                 ${RED}│${NC}"
    echo -e "  ${RED}│${NC}  ${CYAN}Save this password now — it will not be shown${NC}   ${RED}│${NC}"
    echo -e "  ${RED}│${NC}  ${CYAN}again. You can change it from the dashboard.${NC}   ${RED}│${NC}"
    echo -e "  ${RED}└─────────────────────────────────────────────────┘${NC}"
  fi
fi

echo ""
echo -e "  Stop:    ${CYAN}$COMPOSE_CMD down${NC}  (data preserved)"
echo -e "  Reset:   ${RED}$COMPOSE_CMD down -v${NC}  ⚠ DESTROYS ALL DATA"
echo -e "  Logs:    ${CYAN}docker logs phantex-backend -f${NC}"
echo -e "  Update:  ${CYAN}./update.sh${NC}  (safe — back up, migrate, health check)"
echo ""
