// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 The Phantex Authors

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTrustScoreRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// Agent PAID, tool name, resource path, or IP:port
    #[prost(string, tag = "2")]
    pub entity_id: ::prost::alloc::string::String,
    /// "agent" | "tool" | "resource" | "network_dest"
    #[prost(string, tag = "3")]
    pub entity_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTrustScoreResponse {
    #[prost(double, tag = "1")]
    pub trust_score: f64,
    #[prost(message, repeated, tag = "2")]
    pub factors: ::prost::alloc::vec::Vec<TrustFactor>,
    #[prost(message, optional, tag = "3")]
    pub last_updated: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "4")]
    pub entity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub entity_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustFactor {
    /// "history", "behavior", "permissions", "reputation"
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub weight: f64,
    #[prost(double, tag = "3")]
    pub value: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTrustGraphRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub entity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub entity_type: ::prost::alloc::string::String,
    /// How many hops from the entity (default 1)
    #[prost(uint32, tag = "4")]
    pub depth: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustGraphNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub entity_type: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub trust_score: f64,
    #[prost(map = "string, string", tag = "4")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustGraphEdge {
    #[prost(string, tag = "1")]
    pub source_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_id: ::prost::alloc::string::String,
    /// "uses", "accesses", "connects_to", "delegates"
    #[prost(string, tag = "3")]
    pub edge_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub count: u64,
    #[prost(double, tag = "5")]
    pub weight: f64,
    #[prost(message, optional, tag = "6")]
    pub last_seen: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTrustGraphResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<TrustGraphNode>,
    #[prost(message, repeated, tag = "2")]
    pub edges: ::prost::alloc::vec::Vec<TrustGraphEdge>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateEventRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// Agent PAID
    #[prost(string, tag = "2")]
    pub source_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source_type: ::prost::alloc::string::String,
    /// Tool name, resource path, IP:port, or PAID
    #[prost(string, tag = "4")]
    pub target_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub target_type: ::prost::alloc::string::String,
    /// "tool_call", "file_access", "network_connect", "delegation"
    #[prost(string, tag = "6")]
    pub event_type: ::prost::alloc::string::String,
    /// "low", "medium", "high", "critical"
    #[prost(string, tag = "7")]
    pub severity: ::prost::alloc::string::String,
    /// For network events
    #[prost(uint64, tag = "8")]
    pub bytes: u64,
    #[prost(message, optional, tag = "9")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateEventResponse {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    /// Updated trust score for the source
    #[prost(double, tag = "2")]
    pub source_score: f64,
    #[prost(double, tag = "3")]
    pub target_score: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BatchUpdateResponse {
    #[prost(uint64, tag = "1")]
    pub accepted: u64,
    #[prost(uint64, tag = "2")]
    pub rejected: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropagateRequest {
    /// Empty = all tenants
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 0 = use default (20)
    #[prost(uint32, tag = "2")]
    pub max_iterations: u32,
    /// 0 = use default (1e-6)
    #[prost(double, tag = "3")]
    pub convergence_threshold: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PropagateResponse {
    #[prost(uint32, tag = "1")]
    pub iterations: u32,
    #[prost(double, tag = "2")]
    pub max_delta: f64,
    #[prost(bool, tag = "3")]
    pub converged: bool,
    #[prost(uint64, tag = "4")]
    pub nodes_updated: u64,
    #[prost(double, tag = "5")]
    pub elapsed_ms: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    /// "SERVING", "NOT_SERVING"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub total_nodes: u64,
    #[prost(uint64, tag = "3")]
    pub total_edges: u64,
    #[prost(uint64, tag = "4")]
    pub tenants: u64,
    #[prost(double, tag = "5")]
    pub uptime_secs: f64,
}
/// Generated server implementations.
pub mod trust_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TrustServiceServer.
    #[async_trait]
    pub trait TrustService: std::marker::Send + std::marker::Sync + 'static {
        /// Query the trust score for any entity (agent, tool, resource, network dest).
        async fn get_trust_score(
            &self,
            request: tonic::Request<super::GetTrustScoreRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTrustScoreResponse>,
            tonic::Status,
        >;
        /// Return the local neighbourhood of an entity (edges + adjacent nodes).
        async fn get_trust_graph(
            &self,
            request: tonic::Request<super::GetTrustGraphRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTrustGraphResponse>,
            tonic::Status,
        >;
        /// Push a single event update into the trust graph (edge creation / weight update).
        async fn update_event(
            &self,
            request: tonic::Request<super::UpdateEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateEventResponse>,
            tonic::Status,
        >;
        /// Stream many events efficiently (used by the Kafka bridge consumer).
        async fn batch_update_events(
            &self,
            request: tonic::Request<tonic::Streaming<super::UpdateEventRequest>>,
        ) -> std::result::Result<
            tonic::Response<super::BatchUpdateResponse>,
            tonic::Status,
        >;
        /// Trigger a full trust propagation pass (PageRank).
        async fn propagate_scores(
            &self,
            request: tonic::Request<super::PropagateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PropagateResponse>,
            tonic::Status,
        >;
        /// Health probe.
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
    }
    /// TrustService — high-performance trust score queries served by the Rust
    /// trust-engine.  The Python backend uses this to integrate trust scores
    /// into PRL rules and ML features.
    #[derive(Debug)]
    pub struct TrustServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TrustServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TrustServiceServer<T>
    where
        T: TrustService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/phantex.v1.TrustService/GetTrustScore" => {
                    #[allow(non_camel_case_types)]
                    struct GetTrustScoreSvc<T: TrustService>(pub Arc<T>);
                    impl<
                        T: TrustService,
                    > tonic::server::UnaryService<super::GetTrustScoreRequest>
                    for GetTrustScoreSvc<T> {
                        type Response = super::GetTrustScoreResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTrustScoreRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrustService>::get_trust_score(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTrustScoreSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/phantex.v1.TrustService/GetTrustGraph" => {
                    #[allow(non_camel_case_types)]
                    struct GetTrustGraphSvc<T: TrustService>(pub Arc<T>);
                    impl<
                        T: TrustService,
                    > tonic::server::UnaryService<super::GetTrustGraphRequest>
                    for GetTrustGraphSvc<T> {
                        type Response = super::GetTrustGraphResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTrustGraphRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrustService>::get_trust_graph(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTrustGraphSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/phantex.v1.TrustService/UpdateEvent" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateEventSvc<T: TrustService>(pub Arc<T>);
                    impl<
                        T: TrustService,
                    > tonic::server::UnaryService<super::UpdateEventRequest>
                    for UpdateEventSvc<T> {
                        type Response = super::UpdateEventResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateEventRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrustService>::update_event(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateEventSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/phantex.v1.TrustService/BatchUpdateEvents" => {
                    #[allow(non_camel_case_types)]
                    struct BatchUpdateEventsSvc<T: TrustService>(pub Arc<T>);
                    impl<
                        T: TrustService,
                    > tonic::server::ClientStreamingService<super::UpdateEventRequest>
                    for BatchUpdateEventsSvc<T> {
                        type Response = super::BatchUpdateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::UpdateEventRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrustService>::batch_update_events(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchUpdateEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/phantex.v1.TrustService/PropagateScores" => {
                    #[allow(non_camel_case_types)]
                    struct PropagateScoresSvc<T: TrustService>(pub Arc<T>);
                    impl<
                        T: TrustService,
                    > tonic::server::UnaryService<super::PropagateRequest>
                    for PropagateScoresSvc<T> {
                        type Response = super::PropagateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PropagateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrustService>::propagate_scores(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PropagateScoresSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/phantex.v1.TrustService/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: TrustService>(pub Arc<T>);
                    impl<
                        T: TrustService,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TrustService>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthCheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TrustServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "phantex.v1.TrustService";
    impl<T> tonic::server::NamedService for TrustServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
